name: Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Create Executable
        run: make release 
        working-directory: crud
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: crud_binary
          path: crud/target/release/
  
  
  
  
  
  