name: Clippy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
      - name: Run clippy
        run: make lint

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: output.txt